# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- windows

# name: $(Year:yy).$(Month).$(DayOfMonth).$(BuildID)-$(SourceBranchName)

variables:
# script to export all variables to the shell env
# . <(sed -nr '/env_variables:/,$ s/  ([A-Z_]+): (.*)/\1=\2/ p' app.yaml)
  AgentImage: "windows-latest"
  system.debug: true #Setting debug to true will add extra output to the logs but can be useful while trying to determine full reason for failures
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  artifactName: 'Simple3D'
  # extensions:
  #   - {name: "wav", count: 2}
  #   - {name: "dds", count: 5}

stages:
- stage: 'Build_Stage' #Stage name cannot have spaces
  displayName: 'Build'

  jobs:
  - job: 'BuildJob' #Job name cannot have spaces
    displayName: 'Application Build'

    pool:
      vmImage: $(AgentImage)

  - stage: 'BuildAndTest'
    steps:
    - script: #scarica e instala directX
    - task: VSBuild@1 #as well automatically restores packages (alternative to nuget/dotnet restore)
      displayName: 'VS Build & Package restore'
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
    - task: VSTest@2
      displayName: 'VS Test'
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

  - stage: 'Consitancy Check'
    variables:
      DVDsize: 4780
    steps:
  # - template: templates/assetsControl.yml
  #   parameters:
  #     fileExtention: 'wav'
  #     count: 2

  # - template: templates/assetsControl.yml
  #   parameters:
  #     fileExtention: 'dds'
  #     count: 5

    # - script: mail -s "Assets check result" amico@libero.it <<< assetCheck.txt

    #set size flag for the full source code
    - bash: |
        imagesize=$(du -c | tail -1 | awk '{x = $1 / 1024; if (x > $(DVDsize)) {print -1} else {print 0}}')
        echo "##vso[task.setvariable variable=imageSize]$imagesize"
      displayName: 'iso source files size check'
    #iso creation with condition
    - bash: |
        Oscdimg -dn $(Build.SourcesDirectory) $(artifactName)
      displayName: 'iso creation'
      condition: and(succeeded(), eq(variables.imageSize, 0))

  - stage: 'Publish'
    steps:
    - task: PublishBuildArtifacts@1 # recommendded for faster performance
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: $(artifactName)

#https://medium.com/@douglaslassance/automating-unreal-engine-project-builds-for-steam-using-github-4f164c803df0
    # - task: SteamPublish@3
    #   displayName: "Steam publish"
    #     name: "Simple3DGameDX"
    #       appid: 202930
    #       disk_size_mb: $(DVDsize)
    #     targetFolder: '$(Build.ArtifactStagingDirectory)/*.zip'
    #     inputs:
    #       username: $USER
    #       password: $PASS

    # - task:
# Download and debug
    # - task: DownloadBuildArtifacts@0
    #   inputs:
    #     buildType: 'current'
    #     downloadType: 'single'
    #     artifactName: 'drop'
    #     downloadPath: '$(System.ArtifactsDirectory)'

# imageBuild alternative
  # - stage: Deploy
  #   steps:
  #   - task: AzureResourceManagerTemplateDeployment@3
  #     inputs:
  #       deploymentScope: 'Resource Group'
  #       azureResourceManagerConnection: 'ImageBuilder'
  #       subscriptionId: '3a36346f-08ec-4d4a-9f19-60bd98c217c4'
  #       action: 'Create Or Update Resource Group'
  #       resourceGroupName: '$(ResourceGroup)'
  #       location: '$(Location)'
  #       templateLocation: 'Linked artifact'
  #       deploymentMode: 'Incremental'



