# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

# name: $(Year:yy).$(Month).$(DayOfMonth).$(BuildID)-$(SourceBranchName)

variables:
  AgentImage: "windows-2022"
  system.debug: true #Setting debug to true will add extra output to the logs but can be useful while trying to determine full reason for failures
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  artifactName: 'Simple3D'
  assets: 'Assets'
  jsonData: 'JSON'
  imageSize: 4780
  artifactSize: 4780
  videoRes: '3840x2160'

  # extensions:
  #   - {name: "wav", count: 2}
  #   - {name: "dds", count: 5}
  #   - {name: "mpeg", count: 3}

pool:
  vmImage: $(AgentImage)
  demands:
  - msbuild
  - visualstudio
  # - oscdimg
# https://answers.microsoft.com/en-us/windows/forum/all/where-is-oscdimgexe/b6ccd22e-b478-4222-b370-d5aaf021f575
# https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/oscdimg-command-line-options?view=windows-11
  # - DirectX
# https://docs.microsoft.com/en-us/windows/win32/dxtecharts/directx-setup-for-game-developers

jobs:
- job: 'Build'
  displayName: 'Build'
  steps:
  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      restoreSolution: '$(solution)'
      feedsToUse: 'select'

  - task: VSBuild@1
    displayName: 'VS Build'
    inputs:
      solution: '$(solution)'
      msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - task: CopyFiles@2
    inputs:
      contents: '_buildOutput/**'
      targetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
      artifactName: Game

- job: 'ConsistancyCheck'
  displayName: 'Consistancy Check'
  dependsOn: 'Build'
  variables:
    DVDsize: 4780

  steps:
  - template: templates/assetsControl.yml
    parameters:
      fileExtention: 'wav'
      count: 2

  - template: templates/assetsControl.yml
    parameters:
      fileExtention: 'dds'
      count: 5

  - template: templates/assetsControl.yml
    parameters:
      fileExtention: 'mp4'
      count: 1

  - bash: |
      videoRes=$(mediainfo --Inform="Video;%DisplayAspectRatio%" Assets/Cheesy.mp4)
      if [[ $videoRes != $VIDEORES ]]; then
        echo "mp4Res    Failed" >> assetCheck.txt
      else
        echo "mp4Res    Succeded" >> assetCheck.txt
      fi
    displayName: 'mediaInfo resolution check'

  - bash: |
      videoRes=$(ffprobe -v error -select_streams v:0 -show_entries stream=width,height -of csv=s=x:p=0 $(Build.SourcesDirectory)/$(Assets)/*)
      if [[ $videoRes != $VIDEORES ]]; then
        echo "mp4Res    Failed" >> assetCheck.txt
      else
        echo "mp4Res    Succeded" >> assetCheck.txt
      fi
    displayName: 'ffprobe resolution check'


  - bash: |
      fail=$(grep "Failed" assetsCheck.txt)
      if [[ fail == 1 ]]; then
        mail -s "Assets check result" casandra.cubreacov@gmail.com <<< assetCheck.txt
      fi
    displayName: 'send mail with assets check results'

  #set size flag for the full source code
  - bash: |
      imagesize=$(du -c | tail -1 | awk '{x = $1 / 1024; if (x > $(DVDsize)) {print -1} else {print 0}}')
      echo "##vso[task.setvariable variable=imageSize]$imagesize"
    displayName: 'iso source files size check'
    condition: and(succeeded(), eq(variables.imageSize, 0))

  #iso creation with condition
  # - bash: |
      # mkisofs -o $(Build.SourcesDirectory)/$(artifactName).iso -J -R -l $(Build.SourcesDirectory)
  - bash: |
      oscdimg -dn $(Build.SourcesDirectory) $(artifactName)
    displayName: 'iso creation'
    # condition: and(succeeded(), eq(variables.imageSize, 0))

- job: 'Publish'
  displayName: 'Publish'
  dependsOn: 'ConsistancyCheck'
  steps:
  - task: PublishBuildArtifacts@1 # recommendded for faster performance
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: $(artifactName).iso

#https://medium.com/@douglaslassance/automating-unreal-engine-project-builds-for-steam-using-github-4f164c803df0

  # - bash: |
  #     imagesize=$(du $(Build.ArtifactStagingDirectory)/$(artifactName).zip | awk '{print $1}')
  #     echo "##vso[task.setvariable variable=artifactSize]$imagesize"

          # - task: ArchiveFiles@2.
          #   displayName: 'Zip Artifact for Steam'
          #   inputs:
          #     rootFolderOrFile: '$(Build.BinariesDirectory)'
          #     includeRootFolder: true
          #     archiveType: 'zip'
          #     archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
          #     replaceExistingArchive: true

  - bash:
      zipSize=$(du -sh $(Build.ArtifactStagingDirectory)/*.zip | awk '{print $1}')

          # - task: SteamPublish@3
          #   displayName: 'Steam Publish'
          #   name: "Simple3DGameDX"
          #     appid: 202930
          #     disk_size_mb: '$(zipSize)'
          #   targetFolder: '$(Build.ArtifactStagingDirectory)/*.zip'
          #   inputs:
          #     username: $USER
          #     password: $PASS
          #     description: '$(jsonData)/description.json'
    # group: 1

  # https://stackoverflow.com/questions/684015/how-can-i-get-the-resolution-width-and-height-for-a-video-file-from-a-linux-co

          # - task: PublishVideo@2
          #   displayName: 'Realesing video in 4K'
          #   videos:
          #     title: 'Best Game of the Year'
          #     file:  $(assets)/Trailer.mp4
          #     description: $(jsonData)/description.json
          #     category: Music
          #     privacy: private
          #   secrets_path: $(jsonData)/client_secrets.json
          #   credentials_path:  $(jsonData)/credentials.json
          #   condition: and(succeeded(), eq(variables.videoRes),  3840x2160))



